---
- name: Check if Apache is already installed
  stat: path=/etc/init.d/apache2
  register: apache_installed

- name: Update APT Cache
  apt: update_cache=yes cache_valid_time=3600
  when: not apache_installed.stat.exists

- name: Install/Ensure Apache is installed
  apt: 
    name: "{{ apache_packages }}"
    state: "{{ apache_packages_state }}"
