---
- name: Check if MySQL is already installed.
  stat: path=/etc/init.d/mysql
  register: mysql_installed

- name: Update APT Cache
  apt: update_cache=yes cache_valid_time=3600
  when: not mysql_installed.stat.exists

- name: Install/Ensure MySQL is installed
  apt: 
    name: "{{ mysql_packages }}"
    state: "{{ mysql_packages_state }}"
