---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define php_packages.
  set_fact:
    php_packages: "{{ __php_packages | list }}"
  when: php_packages is not defined

- name: Setup Php
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Get installed version of Php.
  command: "{{ php_daemon_path }}{{ php_daemon }} -v"
  changed_when: false
  check_mode: false
  register: _php_version
