---
- name: Check if Php is already installed.
  stat: path=/etc/init.d/php
  register: php_installed

- name: Update APT Cache
  apt: update_cache=yes cache_valid_time=3600
  when: not php_installed.stat.exists

- name: Install/Ensure Php is installed
  apt: 
    name: "{{ php_packages }}"
    state: "{{ php_packages_state }}"
